[package]
name = "regress"
version = "0.2.0"
authors = ["ridiculousfish <corydoras@ridiculousfish.com>"]
description = "A regular expression engine targeting EcmaScript syntax"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ridiculousfish/regress"
keywords = ["regex", "regexp"]
edition = "2018"
readme = "README.md"
default-run = "tester"

[profile.release]

[features]
default = ["backend-pikevm", "cli"]
cli = ["structopt"]

# Enables the PikeVM backend.
backend-pikevm = []

# Prohibits all uses of unsafe code, for the paranoid.
prohibit-unsafe = []

[dependencies]
memchr = "2.3.3"

# Optional dependencies
structopt = { version = "0.3", optional = true}

[[bin]]
name = "tester"
path = "src/bin/tester.rs"
required-features = ["cli"]
