[package]
name = "gen-folds"
version = "0.3.0"
authors = ["ridiculousfish <corydoras@ridiculousfish.com>"]
description = "Create Unicode fold tables"
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "gen-folds"


[[bin]]
name = "gen-folds"
path = "src/gen-folds.rs"
